img = imread('Fig0236(a)(letter_T).tif');
degree = input('degree = ');
scal = input('scaling ratio = ');
x = input('x val = ');
y = input('y val = ');
img_res = imresize(img, scal);
img_trans = imtranslate(img_res, [x, y]);
img_o = imrotate(img_trans, -degree);
img1 = imrotate(img_trans, -degree, 'nearest');
img2 = imrotate(img_trans, -degree, 'bilinear');
img3 = imrotate(img_trans, -degree, 'bicubic');
subplot(1,4,1);
imshow(img_o);
subplot(1,4,2);
imshow(img1);
subplot(1,4,3);
imshow(img2);
subplot(1,4,4);
imshow(img3);
