img = imread('Fig0221(a)(ctskull-256).tif');
a = input('a = ');
b = input('b = ');
c = input('c = ');
d = input('d = ');
e = input('e = ');
f = input('f = ');
g = input('g = ');
h = input('h = ');
subplot(2,4,1);
imshow(grayslice(img,2^a),gray(256));
subplot(2,4,2);
imshow(grayslice(img,2^b),gray(128));
subplot(2,4,3);
imshow(grayslice(img,2^c),gray(64));
subplot(2,4,4);
imshow(grayslice(img,2^d),gray(32));
subplot(2,4,5);
imshow(grayslice(img,2^e),gray(16));
subplot(2,4,6);
imshow(grayslice(img,2^f),gray(8));
subplot(2,4,7);
imshow(grayslice(img,2^g),gray(4));
subplot(2,4,8);
imshow(grayslice(img,2^h),gray(2));